version: '3.3'
services:
  redis:
    image: "redis"
    restart: always
    ports: ['6379:6379']
#    environment:
#      POSTGRES_PASSWORD: qweqwe123
#      POSTGRES_USER: postgres
#      POSTGRES_DB: springbootdb
  redis-demo:
    build: .
    image: redis-demo:1.0
    ports: ['8080:8080']
    volumes:
      - /Users/volodymyr.bakhmatiuk/projects/redis-demo/target:/redis-demo-volume
    links:
      - redis